//! Bindings for the [ARB](https://arblib.org/) library.

// Constants
pub const FMPR_RND_DOWN: u32 = 0;
pub const FMPR_RND_UP: u32 = 1;
pub const FMPR_RND_FLOOR: u32 = 2;
pub const FMPR_RND_CEIL: u32 = 3;
pub const FMPR_RND_NEAR: u32 = 4;
pub const MAG_BITS: u32 = 30;
pub const ARF_RND_DOWN: u32 = 0;
pub const ARF_RND_UP: u32 = 1;
pub const ARF_RND_FLOOR: u32 = 2;
pub const ARF_RND_CEIL: u32 = 3;
pub const ARF_RND_NEAR: u32 = 4;
pub const ARF_RESULT_EXACT: u32 = 0;
pub const ARF_RESULT_INEXACT: u32 = 1;
pub const ARF_EXP_ZERO: u32 = 0;
pub const ARF_NOPTR_LIMBS: u32 = 2;
pub const MUL_MPFR_MIN_LIMBS: u32 = 25;
pub const MUL_MPFR_MAX_LIMBS: u32 = 10000;
pub const ARF_MUL_STACK_ALLOC: u32 = 40;
pub const ARF_MUL_TLS_ALLOC: u32 = 1000;
pub const ARF_ADD_STACK_ALLOC: u32 = 40;
pub const ARF_ADD_TLS_ALLOC: u32 = 1000;
pub const __ARB_VERSION: u32 = 2;
pub const __ARB_VERSION_MINOR: u32 = 20;
pub const __ARB_VERSION_PATCHLEVEL: u32 = 0;
pub const ARB_VERSION: &'static [u8; 7usize] = b"2.20.0\0";
pub const __ARB_RELEASE: u32 = 22000;
pub const ARB_RND: u32 = 0;
pub const ARB_ATAN_TAB1_BITS: u32 = 8;
pub const ARB_ATAN_TAB1_PREC: u32 = 512;
pub const ARB_ATAN_TAB1_LIMBS: u32 = 8;
pub const ARB_ATAN_TAB21_BITS: u32 = 5;
pub const ARB_ATAN_TAB22_BITS: u32 = 5;
pub const ARB_ATAN_TAB2_PREC: u32 = 4608;
pub const ARB_ATAN_TAB2_LIMBS: u32 = 72;
pub const ARB_LOG_TAB11_BITS: u32 = 7;
pub const ARB_LOG_TAB12_BITS: u32 = 7;
pub const ARB_LOG_TAB1_PREC: u32 = 512;
pub const ARB_LOG_TAB1_LIMBS: u32 = 8;
pub const ARB_LOG_TAB21_BITS: u32 = 5;
pub const ARB_LOG_TAB22_BITS: u32 = 5;
pub const ARB_LOG_TAB2_PREC: u32 = 4608;
pub const ARB_LOG_TAB2_LIMBS: u32 = 72;
pub const ARB_EXP_TAB1_NUM: u32 = 178;
pub const ARB_EXP_TAB1_BITS: u32 = 8;
pub const ARB_EXP_TAB1_PREC: u32 = 512;
pub const ARB_EXP_TAB1_LIMBS: u32 = 8;
pub const ARB_EXP_TAB21_NUM: u32 = 23;
pub const ARB_EXP_TAB21_BITS: u32 = 5;
pub const ARB_EXP_TAB22_BITS: u32 = 5;
pub const ARB_EXP_TAB2_PREC: u32 = 4608;
pub const ARB_EXP_TAB2_LIMBS: u32 = 72;
pub const ARB_SIN_COS_TAB1_NUM: u32 = 203;
pub const ARB_SIN_COS_TAB1_BITS: u32 = 8;
pub const ARB_SIN_COS_TAB1_PREC: u32 = 512;
pub const ARB_SIN_COS_TAB1_LIMBS: u32 = 8;
pub const ARB_SIN_COS_TAB21_NUM: u32 = 26;
pub const ARB_SIN_COS_TAB21_BITS: u32 = 5;
pub const ARB_SIN_COS_TAB22_BITS: u32 = 5;
pub const ARB_SIN_COS_TAB2_PREC: u32 = 4608;
pub const ARB_SIN_COS_TAB2_LIMBS: u32 = 72;
pub const ARB_PI4_TAB_LIMBS: u32 = 72;
pub const ACB_LAMBERTW_LEFT: u32 = 2;
pub const ACB_LAMBERTW_MIDDLE: u32 = 4;
pub const FLINT_DEFAULT_THREAD_LIMIT: u32 = 99999;
pub const NMOD_MAT_MUL_TRANSPOSE_CUTOFF: u32 = 20;
pub const NMOD_MAT_SOLVE_TRI_ROWS_CUTOFF: u32 = 64;
pub const NMOD_MAT_SOLVE_TRI_COLS_CUTOFF: u32 = 64;
pub const NMOD_MAT_LU_RECURSIVE_CUTOFF: u32 = 4;
pub const NMOD_MAT_OPTIMAL_MODULUS_BITS: u32 = 59;
pub const NMOD_DIVREM_DIVCONQUER_CUTOFF: u32 = 300;
pub const NMOD_DIV_DIVCONQUER_CUTOFF: u32 = 300;
pub const NMOD_POLY_HGCD_CUTOFF: u32 = 100;
pub const NMOD_POLY_GCD_CUTOFF: u32 = 340;
pub const NMOD_POLY_SMALL_GCD_CUTOFF: u32 = 200;
pub const FMPZ_POLY_INV_NEWTON_CUTOFF: u32 = 32;
pub const FMPZ_POLY_SQRT_DIVCONQUER_CUTOFF: u32 = 16;
pub const FMPZ_POLY_SQRTREM_DIVCONQUER_CUTOFF: u32 = 16;
pub const D_BITS: u32 = 53;
pub const WEAK_CANONICALISE_CUTOFF: u32 = 25600;
pub const ARB_CALC_SUCCESS: u32 = 0;
pub const ARB_CALC_IMPRECISE_INPUT: u32 = 1;
pub const ARB_CALC_NO_CONVERGENCE: u32 = 2;
pub const DLOG_SMALL_LIM: u32 = 50;
pub const DLOG_TABLE_LIM: u32 = 50;
pub const DLOG_TABLE_P_LIM: u32 = 50;
pub const DLOG_TABLE_MODPE_LIM: u32 = 50;
pub const DLOG_TABLE_PE_LIM: u32 = 50;
pub const DLOG_TABLE_N_LIM: u32 = 50;
pub const DLOG_BSGS_LIM: u32 = 500;
pub const DLOG_LOOP_MAX_FACTOR: u32 = 6;
pub const DLOG_G_SMALL: u32 = 0;
pub const DLOG_G_BIG: u32 = 1;
pub const CRT_MAX: u32 = 15;
pub const DFT_VERB: u32 = 0;
pub const MAX_FACTORS: u32 = 15;
pub const ACB_HYPGEOM_2F1_REGULARIZED: u32 = 1;
pub const ACB_HYPGEOM_2F1_AB: u32 = 2;
pub const ACB_HYPGEOM_2F1_AC: u32 = 4;
pub const ACB_HYPGEOM_2F1_BC: u32 = 8;
pub const ACB_HYPGEOM_2F1_ABC: u32 = 16;
pub const ARB_FMPZ_POLY_ROOTS_VERBOSE: u32 = 1;
pub const BELL_NUMBER_TAB_SIZE: u32 = 26;
pub const SMALL_EULER_LIMIT: u32 = 25;
pub const BERNOULLI_SMALL_NUMER_LIMIT: u32 = 35;
pub const BERNOULLI_REV_MIN: u32 = 32;

pub mod acb;
pub mod acb_calc;
pub mod acb_dft;
pub mod acb_dirichlet;
pub mod acb_elliptic;
pub mod acb_hypgeom;
pub mod acb_mat;
pub mod acb_modular;
pub mod acb_poly;
pub mod arb;
pub mod arb_calc;
pub mod arb_fmpz_poly;
pub mod arb_hypgeom;
pub mod arb_mat;
pub mod arb_poly;
pub mod arf;
pub mod arith;
pub mod bernoulli;
pub mod bool_mat;
pub mod dirichlet;
pub mod dlog;
pub mod fmpr;
pub mod hypgeom;
pub mod mag;
pub mod partition;
